#!/usr/bin/env node
// gen-hooks: read hooks.spec.json (single source) and emit per-agent
// hook configs:
//
//   .claude-plugin/plugin.json    (Claude Code — merges `hooks` block)
//   agents/openai.yaml            (Codex CLI — invocation policy)
//   .github/workflows/skill-x-drift.yml (universal CI fallback)
//
// Hook portability is not solved at the config layer — each agent ships
// its own format. This generator paves over the gap from a single spec.
//
// Run with `npm run gen-hooks`.

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

export const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
export const SPEC_PATH = join(REPO_ROOT, "hooks.spec.json");

// --- Pure builders (exported for tests) ---

// Canonical map from spec event name (camelCase, shared with Codex) to the
// Claude Code hook event name (PascalCase). Exported so the spec validator
// can enforce the same enum without two copies drifting.
export const EVENT_MAP = {
  preToolUse: "PreToolUse",
  postToolUse: "PostToolUse",
  sessionStart: "SessionStart",
  sessionEnd: "SessionEnd",
  userPromptSubmitted: "UserPromptSubmit",
  agentStop: "Stop",
  subagentStop: "SubagentStop",
};

export function buildClaudeHooks(spec) {
  const groups = Object.fromEntries(Object.values(EVENT_MAP).map((e) => [e, []]));
  for (const hook of spec.hooks) {
    for (const ev of hook.events) {
      const claudeEvent = EVENT_MAP[ev];
      if (!claudeEvent) {
        throw new Error(
          `gen-hooks: unknown event "${ev}" in hook "${hook.id}". Valid: ${Object.keys(EVENT_MAP).join(", ")}`,
        );
      }
      // `.*` is intentional — Claude matchers regex on tool name; broader file
      // filtering happens inside the hook script (see hook-sync-on-pkg.mjs).
      groups[claudeEvent].push({
        matcher: hook.match?.tool || ".*",
        hooks: [{ type: "command", command: hook.run }],
      });
    }
  }
  const out = {};
  for (const [event, entries] of Object.entries(groups)) {
    if (entries.length > 0) out[event] = entries;
  }
  return out;
}

export function buildCodexYaml(spec) {
  const lines = [
    "# Codex CLI invocation policy for skill-x.",
    "# Generated by tools/gen-hooks.mjs from hooks.spec.json. Do not edit by hand.",
    "name: skill-x",
    `description: ${JSON.stringify(spec.description)}`,
    "hooks:",
  ];
  for (const hook of spec.hooks) {
    lines.push(`  - id: ${hook.id}`);
    lines.push(`    description: ${JSON.stringify(hook.description)}`);
    lines.push("    on:");
    for (const ev of hook.events) lines.push(`      - ${ev}`);
    if (hook.match?.filePattern) {
      lines.push("    when:");
      lines.push(`      file_pattern: ${JSON.stringify(hook.match.filePattern)}`);
    }
    lines.push(`    run: ${JSON.stringify(hook.run)}`);
    lines.push(`    blocking: ${hook.blocking ?? false}`);
  }
  return `${lines.join("\n")}\n`;
}

export function buildGithubWorkflow() {
  return `# Universal CI fallback for skill-x drift detection.
# Fires when package.json is touched and on a daily schedule.
# Generated by tools/gen-hooks.mjs from hooks.spec.json. Do not edit by hand.
name: skill-x drift check

on:
  push:
    paths:
      - "package.json"
      - "skills/**/SKILL.md"
  pull_request:
    paths:
      - "package.json"
      - "skills/**/SKILL.md"
  schedule:
    - cron: "0 6 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - name: Detect upstream drift
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
        run: node tools/sync.mjs --check
      - name: Detect derived-skill staleness
        run: node tools/compose.mjs --check
`;
}

// --- IO orchestration ---

async function emitClaudePlugin(spec) {
  const path = join(REPO_ROOT, ".claude-plugin", "plugin.json");
  const plugin = JSON.parse(await readFile(path, "utf8"));
  plugin.hooks = buildClaudeHooks(spec);
  await writeFile(path, `${JSON.stringify(plugin, null, 2)}\n`, "utf8");
  console.log(`  wrote ${path}`);
}

async function emitCodexPolicy(spec) {
  const dir = join(REPO_ROOT, "agents");
  await mkdir(dir, { recursive: true });
  const path = join(dir, "openai.yaml");
  await writeFile(path, buildCodexYaml(spec), "utf8");
  console.log(`  wrote ${path}`);
}

async function emitGithubWorkflow() {
  const dir = join(REPO_ROOT, ".github", "workflows");
  await mkdir(dir, { recursive: true });
  const path = join(dir, "skill-x-drift.yml");
  await writeFile(path, buildGithubWorkflow(), "utf8");
  console.log(`  wrote ${path}`);
}

async function main() {
  const spec = JSON.parse(await readFile(SPEC_PATH, "utf8"));
  await Promise.all([emitClaudePlugin(spec), emitCodexPolicy(spec), emitGithubWorkflow()]);
  console.log(
    "gen-hooks: emitted Claude plugin.json hooks, Codex openai.yaml, GH Actions workflow",
  );
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
